function g(a){this.c=new h(a)}function h(a){this.c=a}function k(a,b){function c(){return k(a,b.concat(Array.prototype.slice.call(arguments)))}a instanceof g&&(a=l(a));if(void 0===a.apply)return a;void 0===a.arity&&(a.arity=a.length);if(b.length===a.arity)return 1===a.arity?a(b[0]):a.apply(null,b);if(b.length>a.arity)return 1===a.arity?k(a(b.shift()),b):k(a.apply(null,b.splice(0,a.arity)),b);c.arity=a.arity-b.length;return c}function l(a){return a instanceof g?a.c instanceof h?a.c=a.c.c():a.c:a}
var p=new ArrayBuffer(8);new Uint32Array(p);new Float32Array(p);new Float64Array(p);function q(a,b,c){var e=c?c:0;return e>=a.length?l(b):[1,[0,a.charCodeAt(e)],new g(function(){return q(a,b,e+1)})]}function r(a){var b="";for(a=l(a);1==a[0];a=l(a[2]))b+=String.fromCharCode(l(a[1])[1]);return b}function s(a){return a.x}function t(a,b){a.x=b}isDoubleNaN=isNaN;if("undefined"==typeof aa)var aa=void 0;function ba(){var a=r(l(q("Canvas?",[0])));"undefined"!=typeof alert?alert(a):print(a)}
function u(a){var b=0,c=0;a||(a=window.event);if(a.pageX||a.pageY)b=a.pageX,c=a.pageY;else if(a.clientX||a.clientY)b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return[b-a.target.offsetLeft,c-a.target.offsetTop]}
function ca(a,b){var c;switch("mousemove"){case "click":case "dblclick":case "mouseup":case "mousedown":c=function(a){var c=u(a);k(b,[[0,a.button],[0,[0,c[0]],[0,c[1]]],0])};break;case "mousemove":case "mouseover":c=function(a){a=u(a);k(b,[[0,[0,a[0]],[0,a[1]]],0])};break;case "keypress":case "keyup":case "keydown":c=function(a){k(b,[[0,a.keyCode],0])};break;default:c=function(){k(b,[0])}}da(a,c)}
function da(a,b){a.addEventListener?a.addEventListener("mousemove",b,!1):a.attachEvent&&a.attachEvent("onmousemove",b)}function ea(a){var b=l(fa)[1];window.setTimeout(function(){k(a,[0])},b)}function ga(){var a=r(l(q("main",[0])));return(a=document.getElementById(a))?[1,[0,a]]:[0]}function v(a){var b=l(ha)[1],c=[];for(a=l(a);a[0];)a=l(a),c.push(l(a[1])[1]),a=l(a[2]);return c.join(b)}function w(a,b){this.a=[];this.b=b;for(var c=!0,e=a.length-1;0<=e;e--){var d=a[e]|0;c&&d==b||(this.a[e]=d,c=!1)}}
var x={};function z(a){if(-128<=a&&128>a){var b=x[a];if(b)return b}b=new w([a|0],0>a?-1:0);-128<=a&&128>a&&(x[a]=b);return b}function A(a){if(isNaN(a)||!isFinite(a))return B;if(0>a)return C(A(-a));for(var b=[],c=1,e=0;a>=c;e++)b[e]=a/c|0,c*=D;return new w(b,0)}
I_fromString=function(a,b){if(0==a.length)throw Error("number format error: empty string");var c=b||10;if(2>c||36<c)throw Error("radix out of range: "+c);if("-"==a.charAt(0))return C(I_fromString(a.substring(1),c));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character');for(var e=A(Math.pow(c,8)),d=B,f=0;f<a.length;f+=8){var m=Math.min(8,a.length-f),n=parseInt(a.substring(f,f+m),c);8>m?(m=A(Math.pow(c,m)),d=E(F(d,m),A(n))):(d=F(d,e),d=E(d,A(n)))}return d};
var D=4294967296,B=z(0),ia=z(1),ja=z(16777216);function G(a){if(-1==a.b)return-G(C(a));for(var b=0,c=1,e=0;e<a.a.length;e++)var d=H(a,e),b=b+(0<=d?d:D+d)*c,c=c*D;return b}function H(a,b){return 0>b?0:b<a.a.length?a.a[b]:a.b}function I(a){if(0!=a.b)return!1;for(var b=0;b<a.a.length;b++)if(0!=a.a[b])return!1;return!0}function J(a){a=E(a,C(ja));return 0>(-1==a.b?-1:I(a)?0:1)}function C(a){for(var b=a.a.length,c=[],e=0;e<b;e++)c[e]=~a.a[e];a=new w(c,~a.b);return E(a,ia)}
function E(a,b){for(var c=Math.max(a.a.length,b.a.length),e=[],d=0,f=0;f<=c;f++){var m=d+(H(a,f)&65535)+(H(b,f)&65535),n=(m>>>16)+(H(a,f)>>>16)+(H(b,f)>>>16),d=n>>>16,m=m&65535,n=n&65535;e[f]=n<<16|m}return new w(e,e[e.length-1]&-2147483648?-1:0)}
function F(a,b){if(I(a)||I(b))return B;if(-1==a.b)return-1==b.b?F(C(a),C(b)):C(F(C(a),b));if(-1==b.b)return C(F(a,C(b)));if(J(a)&&J(b))return A(G(a)*G(b));for(var c=a.a.length+b.a.length,e=[],d=0;d<2*c;d++)e[d]=0;for(d=0;d<a.a.length;d++)for(var f=0;f<b.a.length;f++){var m=H(a,d)>>>16,n=H(a,d)&65535,y=H(b,f)>>>16,S=H(b,f)&65535;e[2*d+2*f]+=n*S;K(e,2*d+2*f);e[2*d+2*f+1]+=m*S;K(e,2*d+2*f+1);e[2*d+2*f+1]+=n*y;K(e,2*d+2*f+1);e[2*d+2*f+2]+=m*y;K(e,2*d+2*f+2)}for(d=0;d<c;d++)e[d]=e[2*d+1]<<16|e[2*d];for(d=
c;d<2*c;d++)e[d]=0;return new w(e,0)}function K(a,b){for(;(a[b]&65535)!=a[b];)a[b+1]+=a[b]>>>16,a[b]&=65535}function ka(a){a.width=a.width}var fa=[0,20],L=0,M=[0],N=[0,44],ha=new g(function(){return[0,r(M)]}),O=[0,41];function P(a){return[0,String(l(a)[1])]}var Q=[0,0];function la(){return[2]}function R(a,b){var c=l(a);return 0==c[0]?l(b):[1,c[1],new g(function(){return R(c[2],b)})]}
function T(a,b){for(;;){var c=l(a);if(c[0]){var e=c[2],c=l(c[1]);switch(c[0]){case 0:c=k(c[1],[b]);a=R(e,[1,c,M]);continue;case 1:a=R(e,c[1]);continue;default:a=e}}else return L}}var U=[2];function V(){return[2]}
function W(a,b,c){return[0,function(){var e=l(a)[1],d=l(e.x);if(d[0]){var f=l(d[1]);if(f[0])return t(e,[1,f[2]]),[1,[1,new g(function(){return k(c,[L])}),[1,new g(function(){return k(f[1],[b,V])}),M]]];t(e,[0,b,M]);return new g(function(){return k(c,[L])})}t(e,[0,d[1],new g(function(){return R(d[2],[1,[0,b,function(){return k(c,[L])}],M])})]);return U}]}var X=[1,M];
function Y(a,b){return[0,function(){var c=l(a)[1],e=l(c.x);if(e[0])return t(c,[1,new g(function(){return R(e[1],[1,function(a){return function(){return k(b,[a])}},M])})]),U;var d=e[1],f=l(e[2]);if(f[0]){var m=l(f[1]);t(c,[0,m[1],f[2]]);return[1,[1,new g(function(){return k(b,[d])}),[1,new g(function(){return k(m[2],[V])}),M]]]}c.x=X;return new g(function(){return k(b,[d])})}]}
function Z(a){return[0,function(){var b=[0,{x:X}];return[0,function(){ea(function(a){return T([1,new g(function(){return W(b,L,la)}),M],a)});return new g(function(){return Y(b,a)})}]}]}
function $(a,b,c){var e=new g(function(){return $(new g(function(){var b=l(a)[1];return 3.141592653589793>=b?[0,b+0.031415926535897934]:l([0,-3.141592653589793])}),b,c)});return[0,function(){var d=s(l(c)[1]),f=l(d);return 0==f[0]?new g(function(){var c=l(f[1]),d=l(b);return[0,function(b){ka(l(d[2])[1]);k(function(a,b,c){function e(d){var f=l(d);if(f[0]){var m=f[1];return function(d,n){k(new g(function(){var d=new g(function(){return[0,l(c)[1]+6.283185307179586*l(m)[1]/l([0,7])[1]]});return function(a,
b){return function(c,d){var e=l(c),f=e[1],m=f.fillStyle.toString(),n=f.strokeStyle.toString(),y=function(a){var b=l(a);return b[0]?[0,v([1,new g(function(){return[0,"rgba("]}),[1,new g(function(){return P(b[1])}),[1,new g(function(){return[0,r([1,N,M])]}),[1,new g(function(){return P(b[2])}),[1,new g(function(){return[0,r([1,N,M])]}),[1,new g(function(){return P(b[3])}),[1,new g(function(){return[0,r([1,N,M])]}),[1,new g(function(){return P(b[4])}),[1,new g(function(){return[0,r([1,O,M])]}),M]]]]]]]]])]:
[0,v([1,new g(function(){return[0,"rgb("]}),[1,new g(function(){return P(b[1])}),[1,new g(function(){return[0,r([1,N,M])]}),[1,new g(function(){return P(b[2])}),[1,new g(function(){return[0,r([1,N,M])]}),[1,new g(function(){return P(b[3])}),[1,new g(function(){return[0,r([1,O,M])]}),M]]]]]]])]}(a)[1];f.fillStyle=y;f.strokeStyle=y;k(b,[e,d]);f.fillStyle=m;f.strokeStyle=n;return L}}([0,Q,Q,new g(function(){var a=l(m)[1],a=((100*(a&65535)+100*(a&4294901760)+0*(a&65535)|0)&65535)*(a&65535)+((100*(a&65535)+
100*(a&4294901760)+0*(a&65535)|0)&65535)*(a&4294901760)+((100*(a&65535)+100*(a&4294901760)+0*(a&65535)|0)&4294901760)*(a&65535)|0;return[0,155+(a-a%7)/7|0]})],function(c,e){return function(a,b,c){b=l(b);var d=b[1];d.beginPath();k(a,[b,c]);d.fill();return L}(function(c){var e=35*Math.cos(l(d)[1])+l(a)[1],f=35*Math.sin(l(d)[1])+l(b)[1];c=l(c)[1];c.moveTo(e+10,f);c.arc(e,f,10,0,6.283185307179586);return L},c,e)})}),[d,n]);return k(e(f[2]),[d,n])}}return function(){return L}}return e(new g(function(){return function(a,
b){if(a<=b){var c=function(a){return[1,[0,a],new g(function(){return a!=b?c(a+1|0):[0]})]};return c(a)}return[0]}(0,6)}))},[c[1],c[2],a,d[1],b]);return new g(function(){return Z(function(){return l(e)})})}]}):new g(function(){return Z(function(){return l(e)})})}]}
function ma(a){return function(a){var c={x:[0,[0,Q,Q],M]},e=l(ga());if(e[0]){var d=[0,c];return T([1,[0,function(){var a=l(e[1]),b=a[1];if(l(!!b.getContext)){var c=b.getContext("2d");return[0,function(){ca(b,function(a,b){return T([1,new g(function(){return Y(d,function(){return l([0,function(){return new g(function(){return W(d,a,function(){return[2]})})}])})}),M],b)});return[1,[1,U,[1,new g(function(){return $([0,0],[0,[0,c],a],d)}),M]]]}]}return new g(function(){var a=q("Pattern match failure in do expression at Main.hs:29:25-37",
[0]);throw r(a)[1];})}],M],a)}ba();return L}(a)}window.onload=function(){k(ma,[0])};
